import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Three sidebars, matching the three navbar entries:
 *
 *   docsSidebar  hand-written guides and reference prose
 *   apiSidebar   generated from the GraphQL schema — see api-reference/sidebar-schema.js
 *   sdkSidebar   the Ruby and Node.js client libraries
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/introduction",
        "getting-started/quickstart",
        "getting-started/authentication",
        "getting-started/api-keys",
        "getting-started/first-query",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "guides/translations",
        "guides/languages",
        "guides/references",
        "guides/localized-book-names",
        "guides/search",
        "guides/semantic-search",
        "guides/concordance",
        "guides/verse-of-the-day",
        "guides/bible-index",
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: false,
      items: ["reference/errors", "reference/rate-limits", "reference/api-behavior"],
    },
  ],

  // Everything under api-reference/ is generated by `docusaurus graphql-to-doc`, including
  // the _category_.yml files that give Operations and Types their labels — so let
  // autogenerated pick the whole tree up rather than listing pages here.
  apiSidebar: [{ type: "autogenerated", dirName: "api-reference" }],

  sdkSidebar: [
    {
      type: "category",
      label: "SDKs",
      collapsed: false,
      items: ["sdks/index", "sdks/configuration", "sdks/ruby", "sdks/node"],
    },
  ],
};

export default sidebars;
